version: '3'
services:
  db:
    image: postgres:14.8-alpine
    user: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASS}
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U cookie
      interval: 1s
      timeout: 1s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${PROD_DB_USER}:${PROD_DB_PASS}@db:5432/${PROD_DB_NAME}?sslmode=disable",
        "up"
      ]

  app:
    build:
      context: ./
      dockerfile: ./cmd/api/dockerfile
      args:
        DSN: "postgres://${PROD_DB_USER}:${PROD_DB_PASS}@db:5432/${PROD_DB_NAME}?sslmode=disable"
    ports:
      - 4000:4000
    depends_on:
      - migrate
