FROM golang:1.20-alpine as builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o svr cmd/api/*.go

FROM golang:1.20-alpine
ARG DSN
ENV DSN ${DSN}
WORKDIR /app
COPY --from=builder /app/svr /app/svr
EXPOSE 4000
CMD ./svr -db-dsn=${DSN}
