FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN go build -o svr cmd/api/*.go

EXPOSE 4000
CMD [ "./svr", "-db-dsn=postgres://cookie:cookie@cookie-postgres:5432/cookie?sslmode=disable" ]
